from tkinter import *

screen = Tk()
screen.geometry("400x400")
screen.title("ice cream toppings")
label1 = Label(screen,text = "Choose your flavors",font = ("Times New Roman",30))
label1.pack()
hori = Frame(screen)
hori.pack()
flavor1 = Button(hori,text = "chocolate",fg = "white",bg = "#490206")
flavor1.pack(side = LEFT,padx = 10)
flavor2 = Button(hori, text = "cherries",fg = "white",bg = "red")
flavor2.pack(side = LEFT,padx = 10)
flavor3 = Button(hori, text = "pistachio", fg= "white",bg = "green")
flavor3.pack(side = LEFT,padx = 10)
vert = Frame(screen)
vert.pack(side = BOTTOM,pady = 50)
flavor4 = Button(vert,text = "Biscuit",fg = "white",bg = "brown")
flavor4.pack(side = BOTTOM,pady = 20)
flavor5 = Button(vert, text = "Gummy Bears",fg = "white",bg = "blue")
flavor5.pack(side = BOTTOM,pady = 20)
flavor6 = Button(vert, text = "Bubble Gum",fg = "white",bg = "pink")
flavor6.pack(side = BOTTOM,pady = 20)
screen.mainloop()