from tkinter import *
screen = Tk()
screen.geometry("600x400")
screen.config(background="cyan")
#function for storing details
def submit():
    user = entry1.get()
    user2 = entry2.get()
    var = open("details.txt","a")
    var.write(f"username:{user},password:{user2}\n")
    entry1.delete(0,END)
    entry2.delete(0,END)
username = Label(screen,text="Username:",font=("Arial", 15))
username.place(x=60,y=60)
password = Label(screen,text="Password:",font=("Arial", 15))
password.place(x=60,y=110)
entry1 = Entry(screen)
entry1.place(x=200,y=60)
entry2 = Entry(screen,show=".")
entry2.place(x=200,y=110)
button = Button(screen,text="Submit",command=submit)
button.place(x=60,y=165)
screen.mainloop()
