from tkinter import *
screen = Tk()
screen.geometry("600x400")
screen.config(background="cyan")
username = Label(screen,text="Username:",font=("Arial", 15))
username.place(x=60,y=60)
password = Label(screen,text="Password:",font=("Arial", 15))
password.place(x=60,y=110)
entry1 = Entry(screen)
entry1.place(x=200,y=60)
entry2 = Entry(screen)
entry2.place(x=200,y=110)
button = Button(screen,text="Submit")
button.place(x=60,y=165)
screen.mainloop()