from tkinter import *
screen = Tk()
screen.geometry("700x300")
screen.title("Rock Paper Scissors game")
title = Label(screen,text = "Rock Paper Scissors game!",font = ("Arial",20),fg = "Brown",bg = "White")
title.pack()
win = Label(screen,text = "",font = ("Arial",15),fg = "green",bg = "white")
win.pack()
option = Label(screen,text = "Your options:",font = ("Arial",15),fg = "black",bg = "white")
option.place(x=30,y=100)
buttonframe = Frame(screen)
buttonframe.pack(pady = (30,0))
button1 = Button(buttonframe, text = "Rock",font = ("Arial",15),fg = "White",bg = "pink")
button1.pack(side = LEFT,padx = 10)
button2 = Button(buttonframe, text = "Paper",font = ("Arial",15),fg = "White",bg = "aqua")
button2.pack(side = LEFT,padx = 10)
button3 = Button(buttonframe, text = "Scissors",font = ("Arial",15),fg = "White",bg = "green")
button3.pack(side = LEFT,padx = 10)
score = Label(screen,text = "Score:",font = ("Arial",15),fg = "black",bg = "white")
score.place(x=30,y=200)
score1 = Label(screen,text = "You selected:",font = ("Arial",15),fg = "Brown",bg = "White")
score1.place(x=120,y=200)
score2 = Label(screen,text = "Player score:",font = ("Arial",15),fg = "Brown",bg = "White")
score2.place(x=400,y=200)
score3 = Label(screen,text = "Computer selected:",font = ("Arial",15),fg = "Brown",bg = "White")
score3.place(x=120,y=250)
score4 = Label(screen,text = "Computer score:",font = ("Arial",15),fg = "Brown",bg = "White")
score4.place(x=400,y=250)
screen.mainloop()